### Content Based Recommendation System

In [1]:
import pandas as pd

df = pd.read_csv('./movies_metadata.csv')

C:\Users\gopin\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
5,False,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",...,1995-12-15,187436818.0,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Los Angeles Crime Saga,Heat,False,7.7,1886.0
6,False,NaN,58000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,...,1995-12-15,0.0,127.0,"[{'iso_639_1': 'fr', 'name': 'Fran√ßais'}, {'is...",Released,You are cordially invited to the most surprisi...,Sabrina,False,6.2,141.0
7,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,45325,tt0112302,en,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",...,1995-12-22,0.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Original Bad Boys.,Tom and Huck,False,5.4,45.0
8,False,NaN,35000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,9091,tt0114576,en,Sudden Death,International action superstar Jean Claude Van...,...,1995-12-22,64350171.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Terror goes into overtime.,Sudden Death,False,5.5,174.0
9,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,...,1995-11-16,352194034.0,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,GoldenEye,False,6.6,1194.0
10,False,NaN,62000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,9087,tt0112346,en,The American President,"Widowed U.S. president Andrew Shepherd, one of...",...,1995-11-17,107879496.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Why can't the most powerful man in the world h...,The American President,False,6.5,199.0
11,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...",NaN,12110,tt0112896,en,Dracula: Dead and Loving It,When a lawyer shows up at the vampire's doorst...,...,1995-12-22,0.0,88.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Dracula: Dead and Loving It,False,5.7,210.0
12,False,"{'id': 117693, 'name': 'Balto Collection', 'po...",0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",NaN,21032,tt0112453,en,Balto,An outcast half-wolf risks his life to prevent...,...,1995-12-22,11348324.0,78.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Part Dog. Part Wolf. All Hero.,Balto,False,7.1,423.0
13,False,NaN,44000000,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",NaN,10858,tt0113987,en,Nixon,An all-star cast powers this epic look at Amer...,...,1995-12-22,13681765.0,192.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Triumphant in Victory, Bitter in Defeat. He Ch...",Nixon,False,7.1,72.0
14,False,NaN,98000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,1408,tt0112760,en,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",...,1995-12-22,10017322.0,119.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Course Has Been Set. There Is No Turning B...,Cutthroat Island,False,5.7,137.0
15,False,NaN,52000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",NaN,524,tt0112641,en,Casino,The life of the gambling paradise ‚Äì Las Vegas ...,...,1995-11-22,116112375.0,178.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,No one stays at the top forever.,Casino,False,7.8,1343.0
16,False,NaN,16500000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,4584,tt0114388,en,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",...,1995-12-13,135000000.0,136.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Lose your heart and come to your senses.,Sense and Sensibility,False,7.2,364.0
17,False,NaN,4000000,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",NaN,5,tt0113101,en,Four Rooms,It's Ted the Bellhop's first night on the job....,...,1995-12-09,4300000.0,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Twelve outrageous guests. Four scandalous requ...,Four Rooms,False,6.5,539.0
18,False,"{'id': 3167, 'name': 'Ace Ventura Collection',...",30000000,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",NaN,9273,tt0112281,en,Ace Ventura: When Nature Calls,"Summoned from an ashram in Tibet, Ace finds hi...",...,1995-11-10,212385533.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,New animals. New adventures. Same hair.,Ace Ventura: When Nature Calls,False,6.1,1128.0
19,False,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,11517,tt0113845,en,Money Train,A vengeful New York transit cop decides to ste...,...,1995-11-21,35431113.0,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Get on, or GET OUT THE WAY!",Money Train,False,5.4,224.0
20,False,"{'id': 91698, 'name': 'Chili Palmer Collection...",30250000,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...",NaN,8012,tt0113161,en,Get Shorty,Chili Palmer is a Miami mobster who gets sent ...,...,1995-10-20,115101622.0,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"The mob is tough, but it‚Äôs nothing like show b...",Get Shorty,False,6.4,305.0
21,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",NaN,1710,tt0112722,en,Copycat,An agoraphobic psychologist and a female detec...,...,1995-10-27,0.0,124.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,One man is copying the most notorious killers ...,Copycat,False,6.5,199.0
22,False,NaN,50000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,9691,tt0112401,en,Assassins,Assassin Robert Rath arrives at a funeral to k...,...,1995-10-06,30303072.0,132.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"In the shadows of life, In the business of dea...",Assassins,False,6.0,394.0
23,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",NaN,12665,tt0114168,en,Powder,Harassed by classmates who won't accept his sh...,...,1995-10-27,0.0,111.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,An extraordinary encounter with another human ...,Powder,False,6.3,143.0
24,False,NaN,3600000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",http://www.mgm.com/title_title.do?title_star=L...,451,tt0113627,en,Leaving Las Vegas,"Ben Sanderson, an alcoholic Hollywood screenwr...",...,1995-10-27,49800000.0,112.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,I Love You... The Way You Are.,Leaving Las Vegas,False,7.1,365.0
25,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,16420,tt0114057,en,Othello,The evil Iago pretends to be friend of Othello...,...,1995-12-15,0.0,123.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Envy, greed, jealousy and love.",Othello,False,7.0,33.0
26,False,NaN,12000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,9263,tt0114011,en,Now and Then,Waxing nostalgic about the bittersweet passage...,...,1995-10-20,27400000.0,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,In every woman there is the girl she left behind.,Now and Then,False,6.6,91.0
27,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,17015,tt0114117,en,Persuasion,This film adaptation of Jane Austen's last nov...,...,1995-09-27,0.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Persuasion,False,7.4,36.0
28,False,NaN,18000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...",NaN,902,tt0112682,fr,La Cit√© des Enfants Perdus,A scientist in a surrealist society kidnaps ch...,...,1995-05-16,1738611.0,108.0,"[{'iso_639_1': 'cn', 'name': 'ÂπøÂ∑ûËØù / Âª£Â∑ûË©±'}, {'i...",Released,Where happily ever after is just a dream.,The City of Lost Children,False,7.6,308.0
29,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",NaN,37557,tt0115012,zh,ÊëáÂïäÊëáÔºåÊëáÂà∞Â§ñÂ©ÜÊ°•,A provincial boy related to a Shanghai crime f...,...,1995-04-30,0.0,108.0,"[{'iso_639_1': 'zh', 'name': 'ÊôÆÈÄöËØù'}]",Released,In 1930's Shanghai violence was not the proble...,Shanghai Triad,False,6.5,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45436,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 9648, 'n...",NaN,45527,tt1331329,en,The Final Storm,A stranger named Silas flees from a devastatin...,...,2010-01-01,0.0,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Action, Horror",The Final Storm,False,3.7,11.0
45437,False,NaN,0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",NaN,455661,tt6969946,en,In a Heartbeat,A closeted boy runs the risk of being outed by...,...,2017-06-01,0.0,4.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Heart Wants What The Heart Wants,In a Heartbeat,False,8.3,146.0
45438,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,327237,tt3814486,nl,"Bloed, Zweet en Tranen","Bloed, Zweet en Tranen (Blood, Sweat and Tears...",...,2015-04-02,0.0,111.0,"[{'iso_639_1': 'nl', 'name': 'Nederlands'}]",Released,The movie about Andre Hazes,"Blood, Sweat and Tears",False,6.8,11.0
45439,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",NaN,84710,tt0036975,en,Jungle Woman,Paula the ape woman (Acquanetta) is alive and ...,...,1944-06-01,0.0,61.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,RAPTUROUS BEAUTY!...FURY OF A BEAST!,Jungle Woman,False,5.8,2.0
45440,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",NaN,39562,tt0889600,en,To Be Fat Like Me,"Pretty, popular, and slim high-schooler Aly Sc...",...,2007-01-08,0.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,To Be Fat Like Me,False,5.0,12.0
45441,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,14008,tt0294425,en,Cadet Kelly,Hyperactive teenager Kelly is enrolled into a ...,...,2002-03-07,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Too Cool For The Rules!,Cadet Kelly,False,5.2,145.0
45442,False,NaN,0,[],NaN,44330,tt0135690,en,Le tripot clandestin,A combination gambling den and bawdy house is ...,...,1905-01-01,0.0,3.0,[],NaN,NaN,The Scheming Gambler's Paradise,False,5.0,3.0
45443,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",NaN,49279,tt0000359,fr,L'Homme √† la t√™te de caoutchouc,A chemist in his laboratory places upon a tabl...,...,1901-01-01,0.0,3.0,[],Released,NaN,The Man with the Rubber Head,False,7.6,29.0
45444,False,NaN,0,"[{'id': 14, 'name': 'Fantasy'}]",NaN,44333,tt0135179,fr,Les cartes vivantes,A bearded magician holds up a large playing ca...,...,1905-01-01,0.0,3.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,NaN,The Living Playing Cards,False,6.1,8.0
45445,False,NaN,0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...",NaN,49277,tt0135122,en,Les affiches en goguette,A wall full of advertising posters comes to life.,...,1906-01-01,0.0,3.0,"[{'iso_639_1': 'fr', 'name': 'Fran√ßais'}, {'is...",Released,NaN,The Hilarious Posters,False,4.5,2.0
45446,False,NaN,0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...",NaN,49271,tt0127948,en,Le locataire diabolique,A man rents an apartment and furnishes it in r...,...,1909-01-01,0.0,6.0,[],Released,NaN,The Devilish Tenant,False,6.7,12.0
45447,False,NaN,0,[],NaN,44324,tt0135631,fr,Le Roi du maquillage,The background of this picture represents a sc...,...,1904-03-05,0.0,3.0,[],Released,NaN,The Untameable Whiskers,False,6.0,6.0
45448,False,NaN,0,[],NaN,122036,tt0224286,fr,Les Transmutations imperceptibles,This shows a prince entering upon the stage of...,...,1904-01-01,0.0,2.0,[],Released,NaN,The Imperceptable Transmutations,False,5.0,2.0
45449,False,NaN,0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",NaN,14885,tt0457437,en,Pooh's Heffalump Halloween Movie,"It's Halloween in the 100 Acre Wood, and Roo's...",...,2005-09-13,0.0,67.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Celebrate Lumpy's First Halloween.,Pooh's Heffalump Halloween Movie,False,5.4,7.0
45450,False,NaN,0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",NaN,49280,tt0135453,fr,L'Homme orchestre,A band-leader has arranged seven chairs for th...,...,1900-01-01,0.0,1.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,NaN,The One-Man Band,False,6.5,22.0
45451,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",NaN,106807,tt0135571,fr,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,...,1900-01-01,0.0,2.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,NaN,The Fat and Lean Wrestling Match,False,6.5,6.0
45452,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,276895,tt3054038,en,Deep Hearts,"Deep Hearts is a film about the Bororo Fulani,...",...,1981-01-01,0.0,58.0,"[{'iso_639_1': 'ff', 'name': 'Fulfulde'}, {'is...",Released,NaN,Deep Hearts,False,0.0,0.0
45453,False,NaN,0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,404604,tt5690142,hi,Maa,The bliss of a biology teacher‚Äôs family life i...,...,2017-07-07,0.0,146.0,"[{'iso_639_1': 'hi', 'name': '‡§π‡§ø‡§®‡•ç‡§¶‡•Ä'}]",Released,NaN,Mom,False,6.6,14.0
45454,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,420346,tt4130180,en,The Morning After,The Morning After is a feature film that consi...,...,2015-01-11,0.0,79.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What happened last night?,The Morning After,False,4.0,2.0
45455,False,NaN,0,[],NaN,67179,tt0069215,it,San Michele aveva un gallo,Sentenced to life imprisonment for illegal act...,...,1972-01-01,0.0,90.0,"[{'iso_639_1': 'it', 'name': 'Italiano'}]",Released,NaN,St. Michael Had a Rooster,False,6.0,3.0
45456,False,NaN,0,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",NaN,84419,tt0038621,en,House of Horrors,An unsuccessful sculptor saves a madman named ...,...,1946-03-29,0.0,65.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Meet...The CREEPER!,House of Horrors,False,6.3,8.0
45457,False,NaN,0,"[{'id': 9648, 'name': 'Mystery'}, {'id': 27, '...",NaN,390959,tt0265736,en,Shadow of the Blair Witch,"In this true-crime documentary, we delve into ...",...,2000-10-22,0.0,45.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Shadow of the Blair Witch,False,7.0,2.0
45458,False,NaN,0,"[{'id': 27, 'name': 'Horror'}]",NaN,289923,tt0252966,en,The Burkittsville 7,A film archivist revisits the story of Rustin ...,...,2000-10-03,0.0,30.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Do you know what happened 50 years before ""The...",The Burkittsville 7,False,7.0,1.0
45459,False,NaN,0,"[{'id': 878, 'name': 'Science Fiction'}]",NaN,222848,tt0112613,en,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,...,1995-01-01,0.0,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Caged Heat 3000,False,3.5,1.0
45460,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,30840,tt0102797,en,Robin Hood,"Yet another version of the classic epic, with ...",...,1991-05-13,0.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Robin Hood,False,5.7,26.0
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,ÿ±⁄Ø ÿÆŸàÿßÿ®,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'ŸÅÿßÿ±ÿ≥€å'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [3]:
df['tagline'] = df['tagline'].fillna('')
df['overview'] = df['overview'].fillna('')
df['description'] = df['overview'] + df['tagline']

In [4]:
df.shape

(45466, 25)

In [5]:
df.dropna(subset=['description'], inplace=True)
df['title'].drop_duplicates(inplace=True)

In [6]:
df.shape

(45466, 25)

In [7]:
df = df.head(10000)

In [8]:
df.reset_index()

,index,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,description
0,0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,...,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,,Toy Story,False,7.7,5415.0,"Led by Woody, Andy's toys live happily in his ..."
1,1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,...,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,When siblings Judy and Peter discover an encha...
2,2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,...,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,A family wedding reignites the ancient feud be...
3,3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,...,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,"Cheated on, mistreated and stepped on, the wom..."
4,4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,...,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,Just when George Banks has recovered from his ...
5,5,False,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,949,tt0113277,en,Heat,...,187436818.0,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Los Angeles Crime Saga,Heat,False,7.7,1886.0,"Obsessive master thief, Neil McCauley leads a ..."
6,6,False,NaN,58000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,11860,tt0114319,en,Sabrina,...,0.0,127.0,"[{'iso_639_1': 'fr', 'name': 'Fran√ßais'}, {'is...",Released,You are cordially invited to the most surprisi...,Sabrina,False,6.2,141.0,An ugly duckling having undergone a remarkable...
7,7,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,45325,tt0112302,en,Tom and Huck,...,0.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Original Bad Boys.,Tom and Huck,False,5.4,45.0,"A mischievous young boy, Tom Sawyer, witnesses..."
8,8,False,NaN,35000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,9091,tt0114576,en,Sudden Death,...,64350171.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Terror goes into overtime.,Sudden Death,False,5.5,174.0,International action superstar Jean Claude Van...
9,9,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,...,352194034.0,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,GoldenEye,False,6.6,1194.0,James Bond must unmask the mysterious head of ...
10,10,False,NaN,62000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,9087,tt0112346,en,The American President,...,107879496.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Why can't the most powerful man in the world h...,The American President,False,6.5,199.0,"Widowed U.S. president Andrew Shepherd, one of..."
11,11,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...",NaN,12110,tt0112896,en,Dracula: Dead and Loving It,...,0.0,88.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,,Dracula: Dead and Loving It,False,5.7,210.0,When a lawyer shows up at the vampire's doorst...
12,12,False,"{'id': 117693, 'name': 'Balto Collection', 'po...",0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",NaN,21032,tt0112453,en,Balto,...,11348324.0,78.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Part Dog. Part Wolf. All Hero.,Balto,False,7.1,423.0,An outcast half-wolf risks his life to prevent...
13,13,False,NaN,44000000,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",NaN,10858,tt0113987,en,Nixon,...,13681765.0,192.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Triumphant in Victory, Bitter in Defeat. He Ch...",Nixon,False,7.1,72.0,An all-star cast powers this epic look at Amer...
14,14,False,NaN,98000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,1408,tt0112760,en,Cutthroat Island,...,10017322.0,119.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Course Has Been Set. There Is No Turning B...,Cutthroat Island,False,5.7,137.0,"Morgan Adams and her slave, William Shaw, are ..."
15,15,False,NaN,52000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",NaN,524,tt0112641,en,Casino,...,116112375.0,178.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,No one stays at the top forever.,Casino,False,7.8,1343.0,The life of the gambling paradise ‚Äì Las Vegas ...
16,16,False,NaN,16500000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,4584,tt0114388,en,Sense and Sensibility,...,135000000.0,136.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Lose your heart and come to your senses.,Sense and Sensibility,False,7.2,364.0,"Rich Mr. Dashwood dies, leaving his second wif..."
17,17,False,NaN,4000000,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",NaN,5,tt0113101,en,Four Rooms,...,4300000.0,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Twelve outrageous guests. Four scandalous requ...,Four Rooms,False,6.5,539.0,It's Ted the Bellhop's first night on the job....
18,18,False,"{'id': 3167, 'name': 'Ace Ventura Collection',...",30000000,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",NaN,9273,tt0112281,en,Ace Ventura: When Nature Calls,...,212385533.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,New animals. New adventures. Same hair.,Ace Ventura: When Nature Calls,False,6.1,1128.0,"Summoned from an ashram in Tibet, Ace finds hi..."
19,19,False,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,11517,tt0113845,en,Money Train,...,35431113.0,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Get on, or GET OUT THE WAY!",Money Train,False,5.4,224.0,A vengeful New York transit cop decides to ste...
20,20,False,"{'id': 91698, 'name': 'Chili Palmer Collection...",30250000,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...",NaN,8012,tt0113161,en,Get Shorty,...,115101622.0,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"The mob is tough, but it‚Äôs nothing like show b...",Get Shorty,False,6.4,305.0,Chili Palmer is a Miami mobster who gets sent ...
21,21,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",NaN,1710,tt0112722,en,Copycat,...,0.0,124.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,One man is copying the most notorious killers ...,Copycat,False,6.5,199.0,An agoraphobic psychologist and a female detec...
22,22,False,NaN,50000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,9691,tt0112401,en,Assassins,...,30303072.0,132.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"In the shadows of life, In the business of dea...",Assassins,False,6.0,394.0,Assassin Robert Rath arrives at a funeral to k...
23,23,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",NaN,12665,tt0114168,en,Powder,...,0.0,111.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,An extraordinary encounter with another human ...,Powder,False,6.3,143.0,Harassed by classmates who won't accept his sh...
24,24,False,NaN,3600000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",http://www.mgm.com/title_title.do?title_star=L...,451,tt0113627,en,Leaving Las Vegas,...,49800000.0,112.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,I Love You... The Way You Are.,Leaving Las Vegas,False,7.1,365.0,"Ben Sanderson, an alcoholic Hollywood screenwr..."
25,25,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,16420,tt0114057,en,Othello,...,0.0,123.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Envy, greed, jealousy and love.",Othello,False,7.0,33.0,The evil Iago pretends to be friend of Othello...
26,26,False,NaN,12000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,9263,tt0114011,en,Now and Then,...,27400000.0,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,In every woman there is the girl she left behind.,Now and Then,False,6.6,91.0,Waxing nostalgic about the bittersweet passage...
27,27,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,17015,tt0114117,en,Persuasion,...,0.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,,Persuasion,False,7.4,36.0,This film adaptation of Jane Austen's last nov...
28,28,False,NaN,18000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...",NaN,902,tt0112682,fr,La Cit√© des Enfants Perdus,...,1738611.0,108.0,"[{'iso_639_1': 'cn', 'name': 'ÂπøÂ∑ûËØù / Âª£Â∑ûË©±'}, {'i...",Released,Where happily ever after is just a dream.,The City of Lost Children,False,7.6,308.0,A scientist in a surrealist society kidnaps ch...
29,29,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",NaN,37557,tt0115012,zh,ÊëáÂïäÊëáÔºåÊëáÂà∞Â§ñÂ©ÜÊ°•,...,0.0,108.0,"[{'iso_639_1': 'zh', 'name': 'ÊôÆÈÄöËØù'}]",Released,In 1930's Shanghai violence was not the proble...,Shanghai Triad,False,6.5,17.0,A provincial boy related to a Shanghai crime f...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,9970,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,68528,tt0155796,ja,„Ç´„É≥„Çæ„ÉºÂÖàÁîü,...,0.0,128.0,"[{'iso_639_1': 'ja', 'name': 'Êó•Êú¨Ë™û'}]",Released,,Dr. Akagi,False,7.2,6.0,"At the end of WWII, Japanese doctor Akagi sear..."
9971,9971,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...",NaN,185987,tt0097694,ja,Èªí„ÅÑÈõ®,...,0.0,123.0,"[{'iso_639_1': 'ja', 'name': 'Êó•Êú¨Ë™û'}]",Released,,Black Rain,False,7.1,20.0,The story of the aftermath of the Hiroshima bo...
9972,9972,False,NaN,0,"[{'id': 9648, 'name': 'Mystery'}, {'id': 18, '...",NaN,34595,tt0338706,en,Alexandra's Project,...,0.0,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Not everyone loves surprises,Alexandra's Project,False,5.8,24.0,"Steve is a man who has it all, a successful ca..."
9973,9973,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,39851,tt0388838,en,Clean,...,0.0,111.0,"[{'iso_639_1': 'cn', 'name': 'ÂπøÂ∑ûËØù / Âª£Â∑ûË©±'}, {'i...",Released,"When you don't have a choice, you change.",Clean,False,6.7,17.0,"After losing her husband to a heroin overdose,..."
9974,9974,False,NaN,0,[],NaN,45161,tt0325234,en,The Delicate Art of Parking,...,0.0,86.0,[],Released,,The Delicate Art of Parking,False,7.0,2.0,An absurd comedy about a Parking Enforcement O...
9975,9975,False,NaN,2995000,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",NaN,84084,tt0037465,en,Wilson,...,2000000.0,154.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,DRAMA AND SPECTACLE UNPARALLELED! ENTERTAINMEN...,Wilson,False,5.5,2.0,The political career of Woodrow Wilson is chro...
9976,9976,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,84087,tt0033407,en,Blossoms in the Dust,...,0.0,99.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The stirring saga of a childless beauty...who ...,Blossoms in the Dust,False,6.5,11.0,"Edna marries Texan Sam Gladney, operator of a ..."
9977,9977,False,NaN,50000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 35, '...",NaN,7453,tt0371724,en,The Hitchhiker's Guide to the Galaxy,...,104478416.0,109.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Don't leave Earth without it.,The Hitchhiker's Guide to the Galaxy,False,6.6,1340.0,Mere seconds before the Earth is to be demolis...
9978,9978,False,NaN,0,"[{'id': 53, 'name': 'Thriller'}]",NaN,15961,tt0378215,da,Kongekabale,...,0.0,107.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,,King's Game,False,6.9,15.0,Starting a new job as a political journalist a...
9979,9979,False,NaN,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,6183,tt0405743,de,Barfu√ü,...,0.0,110.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,,Barefoot,False,6.7,59.0,"A hedonistic bachelor, falls for an escaped me..."
9980,9980,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,8220,tt0085496,es,Entre tinieblas,...,0.0,114.0,"[{'iso_639_1': 'es', 'name': 'Espa√±ol'}]",Released,,Dark Habits,False,7.4,20.0,A nightclub singer seeks refuge with gay nuns ...
9981,9981,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,35170,tt0078251,en,Snake and Crane Arts of Shaolin,...,0.0,96.0,"[{'iso_639_1': 'cn', 'name': 'ÂπøÂ∑ûËØù / Âª£Â∑ûË©±'}, {'i...",Released,,Snake and Crane Arts of Shaolin,False,6.8,16.0,Jackie Chan stars as the young warrior Hsu Yiu...
9982,9982,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,20187,tt0072926,en,The Eiger Sanction,...,14200000.0,123.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,EASTWOOD is the man . . Eiger is the location ...,The Eiger Sanction,False,6.2,91.0,"A classical art professor and collector, who d..."
9983,9983,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,38151,tt0053957,en,It Started in Naples,...,0.0,100.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,You'll want to be there when the fun starts!,It Started in Naples,False,5.9,11.0,"Mike Hamilton, a Philadelphia lawyer, comes to..."
9984,9984,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,20628,tt0067763,en,Skin Game,...,0.0,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Would you buy a used slave from this man ?,Skin Game,False,6.5,10.0,Quincy Drew (Garner) and Jason O'Rourke (Gosse...
9985,9985,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,43003,tt0072962,en,V√©rit√©s et Mensonges,...,0.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,,F for Fake,False,7.2,77.0,A documentary about fraud and fakery.
9986,9986,False,"{'id': 97919, 'name': 'The Love Comes Softly C...",0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,16250,tt0345591,en,Love Comes Softly,...,0.0,88.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,,Love Comes Softly,False,6.2,25.0,"Marty is a 19 year old pioneer woman, recently..."
9987,9987,False,"{'id': 397842, 'name': 'The Amityville Horror ...",19000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",NaN,10065,tt0384806,en,The Amityville Horror,...,108047131.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What happened over the next 28 days has never ...,The Amityville Horror,False,6.0,606.0,A family is terrorized by demonic forces after...
9988,9988,False,NaN,0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://www.mutantaliensmovie.com/main.html,30863,tt0277909,en,Mutant Aliens,...,0.0,81.0,[],Released,They're freaks coming to kick your butt!,Mutant Aliens,False,7.8,4.0,Mutant Aliens is a wildly humorous yet poignan...
9989,9989,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",NaN,49920,tt0275182,en,Acts of Worship,...,0.0,94.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Rumored,You never know what someone's been through,Acts of Worship,False,6.3,4.0,"Alix is taken in by a photographer, Digna, who..."
9990,9990,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...",NaN,31065,tt0401504,en,Ike: Countdown to D-Day,...,0.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,,Ike: Countdown to D-Day,False,5.7,10.0,This is the story of the senior-level preparat...
9991,9991,False,NaN,500000,"[{'id': 27, 'name': 'Horror'}]",NaN,22033,tt0065597,en,Cry of the Banshee,...,0.0,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Hell hath no fury like a sorceress scorned!,Cry of the Banshee,False,5.5,12.0,In seventeenth century England Lord Whitman wa...
9992,9992,False,NaN,0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,37992,tt0036260,en,Phantom Lady,...,0.0,87.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,IT'S UNIQUE...suspense...mystery...drama!,Phantom Lady,False,6.4,24.0,A mystery woman is a murder suspect's only ali...
9993,9993,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",NaN,32850,tt0041088,en,Act of Violence,...,0.0,82.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The manhunt no woman could stop!,Act of Violence,False,6.2,19.0,An embittered veteran tracks down a POW camp i...
9994,9994,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",NaN,68883,tt0093258,cn,ËÉ≠ËÑÇÊâ£,...,0.0,96.0,"[{'iso_639_1': 'cn', 'name': 'ÂπøÂ∑ûËØù / Âª£Â∑ûË©±'}]",Released,,Rouge,False,6.8,14.0,Fleur is the blue angel in one of Hong Kong's ...
9995,9995,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",NaN,43379,tt0043809,it,Miracolo a Milano,...,0.0,100.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"An impudent, riotous laugh on the lives and mo...",Miracle in Milan,False,7.0,26.0,Once upon a time an old woman discovers a baby...
9996,9996,False,NaN,4500000,"[{'id': 18, 'name': 'Drama'}]",NaN,9393,tt0384369,de,Napola ‚Äì Elite f√ºr den F√ºhrer,...,3764219.0,117.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,Men make history. We make the men.,Before the Fall,False,7.3,74.0,"In 1942, Friedrich Weimer's boxing skills get ..."
9997,9997,False,NaN,9200000,"[{'id': 37, 'name': 'Western'}, {'id': 35, 'na...",NaN,16972,tt0079180,en,The Frisco Kid,...,9346177.0,114.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,,The Frisco Kid,False,6.0,38.0,Rabbi Avram arrives in Philadelphia from Polan...
9998,9998,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",NaN,21325,tt0355857,ja,Onmyoji,...,0.0,112.0,"[{'iso_639_1': 'ja', 'name': 'Êó•Êú¨Ë™û'}, {'iso_639...",Released,,Onmyoji: The Yin Yang Master,False,7.3,3.0,"During a dark time in the Heian period, when e..."
9999,9999,False,"{'id': 124879, 'name': 'State Property Collect...",0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,13409,tt0403537,en,State Property 2,...,1691706.0,94.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,,State Property 2,False,5.5,3.0,Three gangsters vie for control of the streets...

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(analyzer='word', ngram_range=(1, 3), min_df=0, stop_words='english')
tfidf_matrix = tf.fit_transform(df['description'])
print(tfidf_matrix)

  (0, 303373)	0.06151934071917055
  (0, 586922)	0.24739890897855965
  (0, 23231)	0.23840219948682081
  (0, 541414)	0.09293978412969453
  (0, 313146)	0.049881862561919246
  (0, 236471)	0.07454342036606877
  (0, 453542)	0.06566174692143419
  (0, 53344)	0.0729458989504363
  (0, 64792)	0.06217805896790026
  (0, 71621)	0.2833982654125796
  (0, 310308)	0.10415096014897939
  (0, 462379)	0.06566174692143419
  (0, 13727)	0.0767422894791292
  (0, 320478)	0.066478544565774
  (0, 403588)	0.05230107682688081
  (0, 240878)	0.054499945939941216
  (0, 407723)	0.07709401887612567
  (0, 91144)	0.0729458989504363
  (0, 471970)	0.07903601642684246
  (0, 388178)	0.05898704534108736
  (0, 156993)	0.07574772303434206
  (0, 172848)	0.05679367288765451
  (0, 302236)	0.05862643803803276
  (0, 31709)	0.09038918561963764
  (0, 141281)	0.0767422894791292
  :	:
  (9998, 469811)	0.10395676877779507
  (9998, 334904)	0.10395676877779507
  (9998, 375891)	0.10395676877779507
  (9998, 522106)	0.10395676877779507
  (9998, 344846)	0.10395676877779507
  (9998, 92923)	0.10395676877779507
  (9998, 179283)	0.10395676877779507
  (9998, 339440)	0.10395676877779507
  (9998, 151539)	0.10395676877779507
  (9998, 247874)	0.10395676877779507
  (9998, 459913)	0.10395676877779507
  (9998, 252708)	0.10395676877779507
  (9998, 443144)	0.10395676877779507
  (9999, 108939)	0.18112300747486712
  (9999, 508500)	0.19993361501860146
  (9999, 214171)	0.22877900160914974
  (9999, 400692)	0.2497799379616895
  (9999, 564449)	0.2685682158305867
  (9999, 564456)	0.3132330604747395
  (9999, 214232)	0.32717154522631087
  (9999, 109116)	0.32717154522631087
  (9999, 508585)	0.32717154522631087
  (9999, 214233)	0.32717154522631087
  (9999, 564458)	0.32717154522631087
  (9999, 109117)	0.32717154522631087

In [10]:
tfidf_matrix.shape

(10000, 599787)

In [11]:
from sklearn.metrics.pairwise import linear_kernel

cosine_similarities = linear_kernel(tfidf_matrix, tfidf_matrix)

In [12]:
cosine_similarities.shape

(10000, 10000)

In [13]:
cosine_similarities[0].shape

(10000,)

In [14]:
# df = df.reset_index()
titles = df['title']
indices = pd.Series(df.index, index=df['title'])

In [15]:
titles

0                                  Toy Story
1                                    Jumanji
2                           Grumpier Old Men
3                          Waiting to Exhale
4                Father of the Bride Part II
5                                       Heat
6                                    Sabrina
7                               Tom and Huck
8                               Sudden Death
9                                  GoldenEye
10                    The American President
11               Dracula: Dead and Loving It
12                                     Balto
13                                     Nixon
14                          Cutthroat Island
15                                    Casino
16                     Sense and Sensibility
17                                Four Rooms
18            Ace Ventura: When Nature Calls
19                               Money Train
20                                Get Shorty
21                                   Copycat
22                                 Assassins
23                                    Powder
24                         Leaving Las Vegas
25                                   Othello
26                              Now and Then
27                                Persuasion
28                 The City of Lost Children
29                            Shanghai Triad
                        ...
9970                               Dr. Akagi
9971                              Black Rain
9972                     Alexandra's Project
9973                                   Clean
9974             The Delicate Art of Parking
9975                                  Wilson
9976                    Blossoms in the Dust
9977    The Hitchhiker's Guide to the Galaxy
9978                             King's Game
9979                                Barefoot
9980                             Dark Habits
9981         Snake and Crane Arts of Shaolin
9982                      The Eiger Sanction
9983                    It Started in Naples
9984                               Skin Game
9985                              F for Fake
9986                       Love Comes Softly
9987                   The Amityville Horror
9988                           Mutant Aliens
9989                         Acts of Worship
9990                 Ike: Countdown to D-Day
9991                      Cry of the Banshee
9992                            Phantom Lady
9993                         Act of Violence
9994                                   Rouge
9995                        Miracle in Milan
9996                         Before the Fall
9997                          The Frisco Kid
9998            Onmyoji: The Yin Yang Master
9999                        State Property 2
Name: title, Length: 10000, dtype: object

In [16]:
indices

title
Toy Story                                  0
Jumanji                                    1
Grumpier Old Men                           2
Waiting to Exhale                          3
Father of the Bride Part II                4
Heat                                       5
Sabrina                                    6
Tom and Huck                               7
Sudden Death                               8
GoldenEye                                  9
The American President                    10
Dracula: Dead and Loving It               11
Balto                                     12
Nixon                                     13
Cutthroat Island                          14
Casino                                    15
Sense and Sensibility                     16
Four Rooms                                17
Ace Ventura: When Nature Calls            18
Money Train                               19
Get Shorty                                20
Copycat                                   21
Assassins                                 22
Powder                                    23
Leaving Las Vegas                         24
Othello                                   25
Now and Then                              26
Persuasion                                27
The City of Lost Children                 28
Shanghai Triad                            29
                                        ...
Dr. Akagi                               9970
Black Rain                              9971
Alexandra's Project                     9972
Clean                                   9973
The Delicate Art of Parking             9974
Wilson                                  9975
Blossoms in the Dust                    9976
The Hitchhiker's Guide to the Galaxy    9977
King's Game                             9978
Barefoot                                9979
Dark Habits                             9980
Snake and Crane Arts of Shaolin         9981
The Eiger Sanction                      9982
It Started in Naples                    9983
Skin Game                               9984
F for Fake                              9985
Love Comes Softly                       9986
The Amityville Horror                   9987
Mutant Aliens                           9988
Acts of Worship                         9989
Ike: Countdown to D-Day                 9990
Cry of the Banshee                      9991
Phantom Lady                            9992
Act of Violence                         9993
Rouge                                   9994
Miracle in Milan                        9995
Before the Fall                         9996
The Frisco Kid                          9997
Onmyoji: The Yin Yang Master            9998
State Property 2                        9999
Length: 10000, dtype: int64

In [17]:
def recommend(title):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_similarities[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:31]
    movie_indices = [i[0] for i in sim_scores]
    return titles.iloc[movie_indices]

In [18]:
recommend('The Godfather').head(10)

1178     The Godfather: Part II
4324                       Made
5433         Johnny Dangerously
29               Shanghai Triad
6977            Queen of Hearts
8364                       Fury
2891             American Movie
6711                   Mobsters
1914    The Godfather: Part III
5476                    8 Women
Name: title, dtype: object

In [20]:
idx = indices['The Godfather']

In [22]:
idx

834

In [23]:
cosine_similarities[idx]

array([0.        , 0.00171464, 0.00732993, ..., 0.        , 0.        ,
       0.        ])

In [24]:
enumerate(cosine_similarities[idx])

In [25]:
sim_scores = list(enumerate(cosine_similarities[idx]))

In [26]:
sim_scores

[(0, 0.0),
 (1, 0.001714641832736221),
 (2, 0.00732992608933115),
 (3, 0.0),
 (4, 0.001209839294303836),
 (5, 0.0057850809086145046),
 (6, 0.0),
 (7, 0.003065923866538102),
 (8, 0.0),
 (9, 0.0043448061300470206),
 (10, 0.0),
 (11, 0.0),
 (12, 0.0017027471569943616),
 (13, 0.010515673018000726),
 (14, 0.0),
 (15, 0.0021267396370427158),
 (16, 0.0),
 (17, 0.0011590675413474737),
 (18, 0.0),
 (19, 0.0),
 (20, 0.0009020260444793932),
 (21, 0.014608764575034364),
 (22, 0.0018509528426702393),
 (23, 0.0),
 (24, 0.0),
 (25, 0.0),
 (26, 0.0),
 (27, 0.0072527578180679435),
 (28, 0.0),
 (29, 0.039263281451062115),
 (30, 0.0),
 (31, 0.0016953414682855123),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (35, 0.0),
 (36, 0.002396590990763813),
 (37, 0.0),
 (38, 0.0),
 (39, 0.015663756281889662),
 (40, 0.0),
 (41, 0.0),
 (42, 0.001394342803137989),
 (43, 0.0),
 (44, 0.0),
 (45, 0.0017086670480895723),
 (46, 0.0),
 (47, 0.006370268879444701),
 (48, 0.0),
 (49, 0.010405964455322714),
 (50, 0.0),
 (51, 0.002030910436609037),
 (52, 0.003445971551024415),
 (53, 0.004128318608617143),
 (54, 0.0),
 (55, 0.0),
 (56, 0.0038993973700001063),
 (57, 0.006763360060027906),
 (58, 0.0),
 (59, 0.0017811261284049142),
 (60, 0.0),
 (61, 0.0010384615215662284),
 (62, 0.0008561851033686892),
 (63, 0.0),
 (64, 0.0035259288672307484),
 (65, 0.003298786436201208),
 (66, 0.0),
 (67, 0.0),
 (68, 0.0),
 (69, 0.0058042088754763225),
 (70, 0.0),
 (71, 0.0009463923307353015),
 (72, 0.0011491372010091244),
 (73, 0.0),
 (74, 0.001587583311254143),
 (75, 0.0011149804790049952),
 (76, 0.004931897203758379),
 (77, 0.0024191135790074775),
 (78, 0.002086070186567175),
 (79, 0.0),
 (80, 0.0),
 (81, 0.003621663760484816),
 (82, 0.0032942477749005705),
 (83, 0.009755573022765949),
 (84, 0.006242035120815773),
 (85, 0.0),
 (86, 0.008940605814013073),
 (87, 0.00944658738851179),
 (88, 0.0),
 (89, 0.0),
 (90, 0.0),
 (91, 0.0),
 (92, 0.008000384781405532),
 (93, 0.0),
 (94, 0.0),
 (95, 0.0),
 (96, 0.0),
 (97, 0.0),
 (98, 0.0),
 (99, 0.006051285946599436),
 (100, 0.0),
 (101, 0.0),
 (102, 0.0),
 (103, 0.0014293240946703404),
 (104, 0.0),
 (105, 0.0),
 (106, 0.0),
 (107, 0.0),
 (108, 0.0),
 (109, 0.0),
 (110, 0.0),
 (111, 0.0042548561048422135),
 (112, 0.0),
 (113, 0.0018111605043447984),
 (114, 0.003025166609575896),
 (115, 0.0010869304732674264),
 (116, 0.0012751905616400357),
 (117, 0.0045459391529202985),
 (118, 0.0),
 (119, 0.0),
 (120, 0.0),
 (121, 0.0009686599188871011),
 (122, 0.0),
 (123, 0.0042127249367432985),
 (124, 0.0),
 (125, 0.0),
 (126, 0.0027832120354713656),
 (127, 0.0026465662891343783),
 (128, 0.0030751410669427057),
 (129, 0.0),
 (130, 0.0),
 (131, 0.0012940211688942818),
 (132, 0.0),
 (133, 0.005618593481557347),
 (134, 0.0013719631986235834),
 (135, 0.0),
 (136, 0.006167734564562783),
 (137, 0.0),
 (138, 0.0),
 (139, 0.003258089899011491),
 (140, 0.0),
 (141, 0.004548969479664991),
 (142, 0.0032101721406839613),
 (143, 0.0011429518448387243),
 (144, 0.0),
 (145, 0.0),
 (146, 0.0),
 (147, 0.0),
 (148, 0.0032321398201037663),
 (149, 0.0),
 (150, 0.002680301068624166),
 (151, 0.0019360738802057607),
 (152, 0.006815224150887205),
 (153, 0.0),
 (154, 0.006559175720877086),
 (155, 0.0),
 (156, 0.0),
 (157, 0.0),
 (158, 0.012710892591092293),
 (159, 0.0009459686429664913),
 (160, 0.0),
 (161, 0.0),
 (162, 0.0),
 (163, 0.0),
 (164, 0.0),
 (165, 0.0),
 (166, 0.005879561364809296),
 (167, 0.0),
 (168, 0.0),
 (169, 0.0007036316471932102),
 (170, 0.007747159710098271),
 (171, 0.0),
 (172, 0.0),
 (173, 0.0),
 (174, 0.0023191884768011812),
 (175, 0.0),
 (176, 0.0),
 (177, 0.0),
 (178, 0.0),
 (179, 0.0),
 (180, 0.0),
 (181, 0.0031639920569504283),
 (182, 0.0007170192624935121),
 (183, 0.0),
 (184, 0.0008763225810487433),
 (185, 0.0),
 (186, 0.008531439750878266),
 (187, 0.0029945583123452612),
 (188, 0.005555651254459299),
 (189, 0.005090755136866932),
 (190, 0.0),
 (191, 0.0009073754720631003),
 (192, 0.0),
 (193, 0.0),
 (194, 0.0),
 (195, 0.0),
 (196, 0.004853074964224287),
 (197, 0.0),
 (198, 0.004322076273103635),
 (199, 0.0),
 (200, 0.0),
 (201, 0.0),
 (202, 0.0012054489173041897),
 (203, 0.0),
 (204, 0.004297016160176523),
 (205, 0.0),
 (206, 0.0025226890593576384),
 (207, 0.0),
 (208, 0.0035223653306566574),
 (209, 0.0),
 (210, 0.002392858841439965),
 (211, 0.0),
 (212, 0.004608201368689895),
 (213, 0.005760905796404236),
 (214, 0.0),
 (215, 0.0),
 (216, 0.0),
 (217, 0.0),
 (218, 0.0009152296578597418),
 (219, 0.0),
 (220, 0.0),
 (221, 0.0015905922987048756),
 (222, 0.0),
 (223, 0.004813925834795844),
 (224, 0.0009304759762731753),
 (225, 0.0),
 (226, 0.0069269694726760075),
 (227, 0.0),
 (228, 0.006972181558913829),
 (229, 0.0),
 (230, 0.0),
 (231, 0.0),
 (232, 0.0038407989774430227),
 (233, 0.0023733367693239632),
 (234, 0.0008702503543115459),
 (235, 0.005054451664762828),
 (236, 0.0),
 (237, 0.004640694237592122),
 (238, 0.006741169211174862),
 (239, 0.005321424876484771),
 (240, 0.0),
 (241, 0.0),
 (242, 0.0038722037272217896),
 (243, 0.006651577196792401),
 (244, 0.005750609624057756),
 (245, 0.0027264620800268426),
 (246, 0.0),
 (247, 0.0038338928959270584),
 (248, 0.0),
 (249, 0.001742439083725779),
 (250, 0.0009127183255864672),
 (251, 0.021793539674849698),
 (252, 0.0),
 (253, 0.007116254015238494),
 (254, 0.0),
 (255, 0.006441554491692824),
 (256, 0.0),
 (257, 0.0033407390583836682),
 (258, 0.0),
 (259, 0.010991261136392663),
 (260, 0.0),
 (261, 0.0),
 (262, 0.0),
 (263, 0.0),
 (264, 0.009641475807267865),
 (265, 0.0),
 (266, 0.0),
 (267, 0.00165329208784575),
 (268, 0.0),
 (269, 0.0010836456025936974),
 (270, 0.0),
 (271, 0.0),
 (272, 0.0),
 (273, 0.0),
 (274, 0.008301733145345689),
 (275, 0.006836276651484693),
 (276, 0.001685506972549676),
 (277, 0.008801268688454223),
 (278, 0.0),
 (279, 0.0),
 (280, 0.0008704546976034893),
 (281, 0.0),
 (282, 0.0019696743474391294),
 (283, 0.003174259191563611),
 (284, 0.0),
 (285, 0.0),
 (286, 0.012146401043242357),
 (287, 0.0),
 (288, 0.0),
 (289, 0.003210700255174327),
 (290, 0.002640194829460474),
 (291, 0.0020230860700984617),
 (292, 0.006318028701285395),
 (293, 0.0018270934618654787),
 (294, 0.008635155485916167),
 (295, 0.0018911578885027595),
 (296, 0.0031791675675504043),
 (297, 0.0009862609486989242),
 (298, 0.0),
 (299, 0.0),
 (300, 0.0),
 (301, 0.0),
 (302, 0.0),
 (303, 0.002710464642765127),
 (304, 0.0),
 (305, 0.0031439696520530903),
 (306, 0.0),
 (307, 0.0022382776825568425),
 (308, 0.0),
 (309, 0.0),
 (310, 0.001641406115647246),
 (311, 0.010462274225291748),
 (312, 0.0026077868839722387),
 (313, 0.0021828333209052333),
 (314, 0.0009549231784338169),
 (315, 0.0),
 (316, 0.007731821618030486),
 (317, 0.0008001174204220739),
 (318, 0.001792099654315377),
 (319, 0.0048903388784424144),
 (320, 0.0),
 (321, 0.0),
 (322, 0.0),
 (323, 0.0),
 (324, 0.0021991306939822385),
 (325, 0.003137929265921556),
 (326, 0.0),
 (327, 0.0039023067566380356),
 (328, 0.004048634983775499),
 (329, 0.0),
 (330, 0.013439285001619564),
 (331, 0.0),
 (332, 0.008837045813704938),
 (333, 0.006277365069546233),
 (334, 0.0035119892876195906),
 (335, 0.0034607769550762755),
 (336, 0.001028576423550683),
 (337, 0.003919988033144148),
 (338, 0.0),
 (339, 0.0),
 (340, 0.0),
 (341, 0.0),
 (342, 0.0),
 (343, 0.0007133746339761834),
 (344, 0.0),
 (345, 0.0),
 (346, 0.0010300236494711575),
 (347, 0.0),
 (348, 0.0038909220717465373),
 (349, 0.0),
 (350, 0.0031738654384233463),
 (351, 0.0009907269018199015),
 (352, 0.0028652536669228684),
 (353, 0.003916049177832528),
 (354, 0.0),
 (355, 0.001199780149536472),
 (356, 0.0),
 (357, 0.0),
 (358, 0.008163225208742833),
 (359, 0.0031246709505157906),
 (360, 0.0014805133320125207),
 (361, 0.0024786033524368187),
 (362, 0.005454020632726549),
 (363, 0.0),
 (364, 0.0),
 (365, 0.0),
 (366, 0.0),
 (367, 0.001165609578724386),
 (368, 0.004041258688876143),
 (369, 0.003098803563698908),
 (370, 0.009246547650690402),
 (371, 0.013664197871607817),
 (372, 0.0),
 (373, 0.00543394379517226),
 (374, 0.004068906861663143),
 (375, 0.0023891260605571484),
 (376, 0.0012189045012228445),
 (377, 0.0),
 (378, 0.0041706854624600775),
 (379, 0.0),
 (380, 0.0009224502795598075),
 (381, 0.0),
 (382, 0.0),
 (383, 0.0029009715155076297),
 (384, 0.0),
 (385, 0.0030995018753395684),
 (386, 0.006615013082672319),
 (387, 0.00743342582055582),
 (388, 0.0),
 (389, 0.0),
 (390, 0.0),
 (391, 0.0),
 (392, 0.001778130739767061),
 (393, 0.0),
 (394, 0.0),
 (395, 0.0),
 (396, 0.0),
 (397, 0.0),
 (398, 0.0036256969500327385),
 (399, 0.0),
 (400, 0.0),
 (401, 0.016076255373136658),
 (402, 0.0009530906040618737),
 (403, 0.002601399660869124),
 (404, 0.0),
 (405, 0.0031937260355480923),
 (406, 0.0),
 (407, 0.0),
 (408, 0.0),
 (409, 0.0020885834981738747),
 (410, 0.0022359895305263233),
 (411, 0.00133148189319518),
 (412, 0.0),
 (413, 0.0),
 (414, 0.0010600968757419969),
 (415, 0.0),
 (416, 0.0021170797067597592),
 (417, 0.0016772664360558852),
 (418, 0.0),
 (419, 0.0),
 (420, 0.0008312734174241921),
 (421, 0.0026305454223241433),
 (422, 0.0012310455046673993),
 (423, 0.006401998395139481),
 (424, 0.0),
 (425, 0.0),
 (426, 0.0013671216278264334),
 (427, 0.003195923072331585),
 (428, 0.0),
 (429, 0.0),
 (430, 0.0009818362975543007),
 (431, 0.0),
 (432, 0.004723690498347109),
 (433, 0.0),
 (434, 0.0014117519447918825),
 (435, 0.0),
 (436, 0.0),
 (437, 0.0),
 (438, 0.009747716434810656),
 (439, 0.0),
 (440, 0.003171331249810716),
 (441, 0.0018607539543660698),
 (442, 0.0),
 (443, 0.0009991139579758942),
 (444, 0.0),
 (445, 0.0012256989224400405),
 (446, 0.010043502014126944),
 (447, 0.00292836169313919),
 (448, 0.0),
 (449, 0.012968118904788264),
 (450, 0.002714193334803428),
 (451, 0.006389231295988721),
 (452, 0.0030323942365905335),
 (453, 0.0009914032874854635),
 (454, 0.0),
 (455, 0.0016415695640516585),
 (456, 0.0),
 (457, 0.0),
 (458, 0.0),
 (459, 0.0),
 (460, 0.0),
 (461, 0.0),
 (462, 0.0),
 (463, 0.0),
 (464, 0.010938965278038882),
 (465, 0.0),
 (466, 0.0),
 (467, 0.002863875860721648),
 (468, 0.0),
 (469, 0.0027816846175652563),
 (470, 0.006918516242714002),
 (471, 0.0),
 (472, 0.0),
 (473, 0.005400331765616154),
 (474, 0.0),
 (475, 0.001762419168882528),
 (476, 0.0),
 (477, 0.006935740941864452),
 (478, 0.0),
 (479, 0.003700588887090525),
 (480, 0.007949605993913453),
 (481, 0.010162086262580958),
 (482, 0.0),
 (483, 0.0),
 (484, 0.0),
 (485, 0.0),
 (486, 0.0015291987595388433),
 (487, 0.0),
 (488, 0.001275719663960968),
 (489, 0.0),
 (490, 0.0014987241828343747),
 (491, 0.007186955189346642),
 (492, 0.0029456503141013332),
 (493, 0.0),
 (494, 0.001605061234343509),
 (495, 0.0),
 (496, 0.004070536001197649),
 (497, 0.0),
 (498, 0.0),
 (499, 0.0),
 (500, 0.007721946347537464),
 (501, 0.0),
 (502, 0.0),
 (503, 0.0),
 (504, 0.0038844891135801454),
 (505, 0.0029726876028574327),
 (506, 0.0),
 (507, 0.007955044861579129),
 (508, 0.0),
 (509, 0.005505637221372668),
 (510, 0.0),
 (511, 0.0),
 (512, 0.0),
 (513, 0.0),
 (514, 0.0),
 (515, 0.0),
 (516, 0.0),
 (517, 0.0),
 (518, 0.001880609188876),
 (519, 0.0),
 (520, 0.005247013645651839),
 (521, 0.0),
 (522, 0.0014531221222312683),
 (523, 0.0),
 (524, 0.0),
 (525, 0.005401611605254706),
 (526, 0.0016100736935196415),
 (527, 0.010155377434056603),
 (528, 0.0),
 (529, 0.001841629042885922),
 (530, 0.0020909654269881156),
 (531, 0.005776953356603108),
 (532, 0.0),
 (533, 0.006803846066059079),
 (534, 0.0),
 (535, 0.0016010652820209678),
 (536, 0.0012137597262825257),
 (537, 0.0008706956842454089),
 (538, 0.0),
 (539, 0.002768079554687133),
 (540, 0.0),
 (541, 0.0),
 (542, 0.0),
 (543, 0.0),
 (544, 0.0017397233946832066),
 (545, 0.0),
 (546, 0.0),
 (547, 0.0),
 (548, 0.0),
 (549, 0.006075382427072456),
 (550, 0.0),
 (551, 0.008130775359527474),
 (552, 0.0),
 (553, 0.0),
 (554, 0.0),
 (555, 0.0008441712754481185),
 (556, 0.0015808670959980807),
 (557, 0.0),
 (558, 0.0),
 (559, 0.008118138397747984),
 (560, 0.001075451044149117),
 (561, 0.0018593669494828564),
 (562, 0.0),
 (563, 0.0018732427386159223),
 (564, 0.0),
 (565, 0.0031579192414949936),
 (566, 0.0),
 (567, 0.0059427262623672865),
 (568, 0.0018740856710228733),
 (569, 0.0011137713060813117),
 (570, 0.0),
 (571, 0.004949989033569673),
 (572, 0.0),
 (573, 0.008233200395418418),
 (574, 0.0),
 (575, 0.002830608279461709),
 (576, 0.00876191060092335),
 (577, 0.0017783500445102875),
 (578, 0.00719129177262871),
 (579, 0.008663727434147051),
 (580, 0.0),
 (581, 0.0),
 (582, 0.00819795996497039),
 (583, 0.0),
 (584, 0.0),
 (585, 0.007533821153826826),
 (586, 0.004950919978363469),
 (587, 0.0),
 (588, 0.0),
 (589, 0.000829596340614168),
 (590, 0.0),
 (591, 0.0),
 (592, 0.0),
 (593, 0.0),
 (594, 0.006916777084386317),
 (595, 0.0),
 (596, 0.0),
 (597, 0.0),
 (598, 0.0),
 (599, 0.0),
 (600, 0.0),
 (601, 0.003324823735755439),
 (602, 0.0),
 (603, 0.0),
 (604, 0.0009775948074815508),
 (605, 0.0),
 (606, 0.0),
 (607, 0.009857109551977942),
 (608, 0.0029731571703042574),
 (609, 0.001019797772902577),
 (610, 0.0),
 (611, 0.0),
 (612, 0.0),
 (613, 0.0019177511222828356),
 (614, 0.0),
 (615, 0.0),
 (616, 0.0),
 (617, 0.0008142906986197378),
 (618, 0.0015809882186557627),
 (619, 0.005495006689153876),
 (620, 0.0),
 (621, 0.003147396927742391),
 (622, 0.0),
 (623, 0.0),
 (624, 0.0006426647138479345),
 (625, 0.0),
 (626, 0.009617686195274151),
 (627, 0.0),
 (628, 0.0),
 (629, 0.0),
 (630, 0.0016962162461393335),
 (631, 0.003137285913523763),
 (632, 0.002906609650580825),
 (633, 0.0015977743653207022),
 (634, 0.0),
 (635, 0.0),
 (636, 0.0019908352220809125),
 (637, 0.0),
 (638, 0.0),
 (639, 0.0028322141076826384),
 (640, 0.0033209681379481994),
 (641, 0.0),
 (642, 0.0),
 (643, 0.0),
 (644, 0.0),
 (645, 0.0),
 (646, 0.0),
 (647, 0.003420425607515511),
 (648, 0.0017772884359939936),
 (649, 0.0),
 (650, 0.004051396873761972),
 (651, 0.0),
 (652, 0.0),
 (653, 0.0),
 (654, 0.0),
 (655, 0.000878866536598763),
 (656, 0.0),
 (657, 0.002364913851177835),
 (658, 0.006833297692070578),
 (659, 0.0),
 (660, 0.0),
 (661, 0.017748320993361693),
 (662, 0.010317805566520689),
 (663, 0.0),
 (664, 0.007016206530757221),
 (665, 0.0),
 (666, 0.010150043435728315),
 (667, 0.004475002224720704),
 (668, 0.0024270477228837415),
 (669, 0.003841748440093753),
 (670, 0.002050739669503109),
 (671, 0.0),
 (672, 0.0),
 (673, 0.0029248202155620433),
 (674, 0.0025245940764380605),
 (675, 0.0),
 (676, 0.0058517767792406),
 (677, 0.0),
 (678, 0.0019273903610914644),
 (679, 0.0),
 (680, 0.0),
 (681, 0.0),
 (682, 0.0),
 (683, 0.0),
 (684, 0.00495184261102099),
 (685, 0.0),
 (686, 0.0),
 (687, 0.004766971749098189),
 (688, 0.0),
 (689, 0.0009582124231002571),
 (690, 0.0),
 (691, 0.0),
 (692, 0.0),
 (693, 0.00943432668233281),
 (694, 0.0),
 (695, 0.0009597907783872316),
 (696, 0.0),
 (697, 0.0009859958838765587),
 (698, 0.0),
 (699, 0.0),
 (700, 0.0031215597913333607),
 (701, 0.0),
 (702, 0.0),
 (703, 0.0),
 (704, 0.0),
 (705, 0.0023073276304465097),
 (706, 0.0022930137587786423),
 (707, 0.0),
 (708, 0.0),
 (709, 0.0),
 (710, 0.006051021512395598),
 (711, 0.002227880412948177),
 (712, 0.0026066986883004736),
 (713, 0.0),
 (714, 0.004544759879234191),
 (715, 0.001962119256839843),
 (716, 0.0),
 (717, 0.0),
 (718, 0.0),
 (719, 0.003273478904482581),
 (720, 0.0),
 (721, 0.0032664255831412452),
 (722, 0.0),
 (723, 0.0),
 (724, 0.02674887043631316),
 (725, 0.0),
 (726, 0.004648776769462047),
 (727, 0.0),
 (728, 0.0),
 (729, 0.00781635329003633),
 (730, 0.0),
 (731, 0.0034701670987919817),
 (732, 0.0),
 (733, 0.0),
 (734, 0.0),
 (735, 0.007876254321760904),
 (736, 0.0),
 (737, 0.005990341213137358),
 (738, 0.0),
 (739, 0.0016851796132480875),
 (740, 0.0),
 (741, 0.0),
 (742, 0.0036307291182016985),
 (743, 0.0),
 (744, 0.0),
 (745, 0.01414111188757434),
 (746, 0.0),
 (747, 0.001561667693428647),
 (748, 0.0),
 (749, 0.005538428546677886),
 (750, 0.0025300085649106853),
 (751, 0.0),
 (752, 0.005385883643651207),
 (753, 0.0016178848663047408),
 (754, 0.005458396151639839),
 (755, 0.00364316122465161),
 (756, 0.0037611787286853148),
 (757, 0.011522978718635375),
 (758, 0.0016819555166368808),
 (759, 0.015489987321769831),
 (760, 0.0),
 (761, 0.013080108715182802),
 (762, 0.0),
 (763, 0.0),
 (764, 0.0),
 (765, 0.0),
 (766, 0.0009981696150954294),
 (767, 0.0),
 (768, 0.0),
 (769, 0.0007080040209245091),
 (770, 0.003514197620809177),
 (771, 0.0),
 (772, 0.0),
 (773, 0.0008691951073337983),
 (774, 0.0),
 (775, 0.0),
 (776, 0.0),
 (777, 0.0),
 (778, 0.0),
 (779, 0.008015459717862604),
 (780, 0.0),
 (781, 0.00171329327555352),
 (782, 0.0),
 (783, 0.0),
 (784, 0.0),
 (785, 0.0),
 (786, 0.0),
 (787, 0.0),
 (788, 0.0),
 (789, 0.0),
 (790, 0.0),
 (791, 0.0007725397378338958),
 (792, 0.0),
 (793, 0.0),
 (794, 0.0),
 (795, 0.0),
 (796, 0.0),
 (797, 0.0020486865013931324),
 (798, 0.001390457601587277),
 (799, 0.0),
 (800, 0.0),
 (801, 0.0007925809524706081),
 (802, 0.0),
 (803, 0.00826695962064921),
 (804, 0.0011367869554596568),
 (805, 0.0),
 (806, 0.0032037861204554374),
 (807, 0.0),
 (808, 0.004027105116682948),
 (809, 0.0),
 (810, 0.0),
 (811, 0.002322944200553193),
 (812, 0.0),
 (813, 0.0),
 (814, 0.0),
 (815, 0.006347655583186177),
 (816, 0.001900954018665213),
 (817, 0.0),
 (818, 0.0),
 (819, 0.0),
 (820, 0.0012421853424433517),
 (821, 0.0),
 (822, 0.0),
 (823, 0.000757481636680248),
 (824, 0.0),
 (825, 0.0),
 (826, 0.0059163608828105355),
 (827, 0.0017989931054825485),
 (828, 0.0),
 (829, 0.004486645838360504),
 (830, 0.009605811998538997),
 (831, 0.0),
 (832, 0.0),
 (833, 0.0),
 (834, 1.0000000000000013),
 (835, 0.0),
 (836, 0.0),
 (837, 0.0),
 (838, 0.0016110206442695183),
 (839, 0.0),
 (840, 0.0),
 (841, 0.0030164646431069925),
 (842, 0.0),
 (843, 0.0),
 (844, 0.0),
 (845, 0.0),
 (846, 0.0),
 (847, 0.005022210251197791),
 (848, 0.0009236742358489073),
 (849, 0.007991829205657029),
 (850, 0.017328990502816364),
 (851, 0.0027793129751684056),
 (852, 0.0006240819248879451),
 (853, 0.0),
 (854, 0.0),
 (855, 0.004698389928838555),
 (856, 0.0),
 (857, 0.008609523000664237),
 (858, 0.0),
 (859, 0.0),
 (860, 0.0037905311146601323),
 (861, 0.0),
 (862, 0.0007729571919319817),
 (863, 0.0),
 (864, 0.016525372241206645),
 (865, 0.0),
 (866, 0.006783279789670039),
 (867, 0.0),
 (868, 0.0),
 (869, 0.0),
 (870, 0.0),
 (871, 0.001513528789546792),
 (872, 0.0),
 (873, 0.0020820778281276636),
 (874, 0.0),
 (875, 0.0),
 (876, 0.0),
 (877, 0.005052885230774843),
 (878, 0.0),
 (879, 0.0013510121262371609),
 (880, 0.0),
 (881, 0.0),
 (882, 0.0),
 (883, 0.0),
 (884, 0.0),
 (885, 0.003317517007706948),
 (886, 0.0),
 (887, 0.0),
 (888, 0.01016853342731057),
 (889, 0.0018914706645336403),
 (890, 0.0015121069592704502),
 (891, 0.0015145683903261813),
 (892, 0.0),
 (893, 0.006290635614433942),
 (894, 0.0023419806308393053),
 (895, 0.0),
 (896, 0.0012649103487191577),
 (897, 0.0),
 (898, 0.0),
 (899, 0.0),
 (900, 0.0),
 (901, 0.0),
 (902, 0.01079188316116076),
 (903, 0.0024333118130357282),
 (904, 0.0),
 (905, 0.0006995757590300054),
 (906, 0.0),
 (907, 0.0),
 (908, 0.0),
 (909, 0.0),
 (910, 0.0),
 (911, 0.0),
 (912, 0.0026167215142841815),
 (913, 0.0),
 (914, 0.0031027344300666323),
 (915, 0.0),
 (916, 0.0),
 (917, 0.0),
 (918, 0.005998983861755628),
 (919, 0.0),
 (920, 0.007348004432046656),
 (921, 0.007120793857569495),
 (922, 0.0044747291106103535),
 (923, 0.0),
 (924, 0.0),
 (925, 0.0),
 (926, 0.0008345517394471911),
 (927, 0.0),
 (928, 0.0),
 (929, 0.0),
 (930, 0.00238787222326822),
 (931, 0.0),
 (932, 0.0),
 (933, 0.0019170766532428938),
 (934, 0.0036471964497361803),
 (935, 0.0),
 (936, 0.0),
 (937, 0.012178113870703432),
 (938, 0.005859802813045895),
 (939, 0.005287372857238204),
 (940, 0.0),
 (941, 0.0),
 (942, 0.0),
 (943, 0.0040516081211495756),
 (944, 0.0024247242173364766),
 (945, 0.0010848819657009751),
 (946, 0.0),
 (947, 0.0),
 (948, 0.0),
 (949, 0.0018698502660502948),
 (950, 0.0),
 (951, 0.0),
 (952, 0.0),
 (953, 0.003890702237003558),
 (954, 0.0019312106425175962),
 (955, 0.0),
 (956, 0.0),
 (957, 0.0),
 (958, 0.00877961233419983),
 (959, 0.0),
 (960, 0.002798877406582342),
 (961, 0.0),
 (962, 0.0),

In [27]:
sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

In [28]:
sim_scores

[(834, 1.0000000000000013),
 (1178, 0.14992200033931688),
 (4324, 0.04021684976693453),
 (5433, 0.039311985383549956),
 (29, 0.039263281451062115),
 (6977, 0.03890199598661835),
 (8364, 0.035184062488509214),
 (2891, 0.0338554146883491),
 (6711, 0.031712633383547024),
 (1914, 0.030150463453486608),
 (5476, 0.029117000357142646),
 (5689, 0.027081639574887587),
 (2624, 0.026825525125295048),
 (724, 0.02674887043631316),
 (4473, 0.025911994676770758),
 (9216, 0.025601002253174937),
 (3998, 0.025554387762630137),
 (2587, 0.025546375052027726),
 (4618, 0.02537172801173615),
 (7765, 0.024745228517596127),
 (4464, 0.024057529584514546),
 (4396, 0.023997651259148142),
 (8653, 0.02341847975634212),
 (8191, 0.023222283257004456),
 (7515, 0.02287073390869033),
 (5330, 0.021847090088984458),
 (251, 0.021793539674849698),
 (6822, 0.021495331464793044),
 (1874, 0.021411146240112207),
 (7731, 0.020920943247186612),
 (3291, 0.020754939932866246),
 (5367, 0.02064029870535035),
 (5381, 0.020621375732149227),
 (5822, 0.020226743321377406),
 (7420, 0.020115771106831937),
 (7588, 0.020091331419737738),
 (2015, 0.01998169078682876),
 (5463, 0.01956522013582225),
 (2765, 0.01907577353926073),
 (975, 0.018976489092836255),
 (6152, 0.018374710076309753),
 (1506, 0.017925484380444907),
 (6042, 0.01787989855977826),
 (1677, 0.017750697995824856),
 (661, 0.017748320993361693),
 (6620, 0.017513969790352364),
 (6142, 0.01738915087053345),
 (8583, 0.01736968859626583),
 (850, 0.017328990502816364),
 (8113, 0.017117974987884713),
 (7608, 0.01673777731317734),
 (864, 0.016525372241206645),
 (9157, 0.01646476259327736),
 (6689, 0.01641210895393338),
 (401, 0.016076255373136658),
 (9786, 0.016056096110980026),
 (4356, 0.015807956906615316),
 (1876, 0.015776985329685654),
 (39, 0.015663756281889662),
 (7596, 0.015554246961449643),
 (9059, 0.015545494688384374),
 (759, 0.015489987321769831),
 (3253, 0.015407485869878574),
 (1377, 0.015344109039397539),
 (7869, 0.015339508673056362),
 (5917, 0.015309829505503341),
 (4785, 0.015243207771176564),
 (6552, 0.01520478668004108),
 (6813, 0.015141024950546672),
 (5180, 0.015057535895064669),
 (5873, 0.014937337636896138),
 (3857, 0.014655945319849251),
 (1854, 0.014639811999756563),
 (7225, 0.014629071963798309),
 (21, 0.014608764575034364),
 (3603, 0.014518410225352406),
 (9796, 0.014468710891823285),
 (1129, 0.01444881404483478),
 (3760, 0.014443103549948435),
 (6271, 0.014415090841535642),
 (5157, 0.014394346925954581),
 (5884, 0.014291698804547176),
 (7781, 0.014201004851987628),
 (745, 0.01414111188757434),
 (4033, 0.014020282767954244),
 (4454, 0.013960130169760405),
 (1128, 0.013921824592731162),
 (1185, 0.013831674803437579),
 (2211, 0.013798674584420953),
 (6274, 0.01379506385511653),
 (6325, 0.01372371125740992),
 (371, 0.013664197871607817),
 (2433, 0.013592897990176557),
 (6276, 0.013591509468993486),
 (3385, 0.01346917760012848),
 (3625, 0.013460262172738357),
 (2067, 0.01345065349885631),
 (330, 0.013439285001619564),
 (2399, 0.013362385917197506),
 (4598, 0.013360991020278483),
 (5139, 0.013299025439639761),
 (9633, 0.013279822274215099),
 (8010, 0.013256048545836056),
 (5596, 0.013253818336449532),
 (9365, 0.013187391955912358),
 (1147, 0.01317147117509676),
 (1179, 0.01313045824301739),
 (761, 0.013080108715182802),
 (1700, 0.013058817350374586),
 (4714, 0.012988632332932612),
 (7272, 0.012978864517541676),
 (449, 0.012968118904788264),
 (4678, 0.012949805127576524),
 (7430, 0.012923026654413935),
 (4739, 0.0129179123558761),
 (4516, 0.012890052467651743),
 (3498, 0.01288978771139956),
 (9308, 0.012855326527546616),
 (2474, 0.012832922695229506),
 (7963, 0.01282312372608763),
 (8925, 0.01275706269313803),
 (8853, 0.012750734363888504),
 (158, 0.012710892591092293),
 (7980, 0.012678805301111628),
 (4565, 0.012644558454399915),
 (4409, 0.012635607537596572),
 (1296, 0.012634005470869855),
 (7621, 0.012608952285942165),
 (3896, 0.01260345568909366),
 (2690, 0.01258354268905525),
 (6250, 0.012569861389692237),
 (1939, 0.012552608511676722),
 (7134, 0.012540629738875),
 (2107, 0.012530332939625887),
 (1556, 0.012487836590906347),
 (7971, 0.012278695216928835),
 (6696, 0.012256517286059926),
 (1190, 0.012255260815145413),
 (1902, 0.012213118872418185),
 (937, 0.012178113870703432),
 (1846, 0.012154524798718223),
 (286, 0.012146401043242357),
 (7516, 0.01213026598890873),
 (4071, 0.012122710892206316),
 (7850, 0.012094817461932106),
 (1599, 0.01208911311675837),
 (2501, 0.01207989563617643),
 (4607, 0.012062176699787845),
 (7093, 0.011991824620620713),
 (3248, 0.011964049012846072),
 (8198, 0.01194296755913974),
 (5429, 0.0119146139031138),
 (4250, 0.011864759228114754),
 (9862, 0.011842916035521291),
 (8501, 0.011817313264248529),
 (3087, 0.011796519609244676),
 (3131, 0.011739280831203035),
 (2163, 0.011726276315521115),
 (4729, 0.011726181665148702),
 (9647, 0.011715104853316408),
 (4308, 0.01170849678019182),
 (5273, 0.011687024598152271),
 (6770, 0.011671242212564322),
 (3918, 0.011669652204712647),
 (983, 0.011657802520511434),
 (1253, 0.01165231847317562),
 (3039, 0.01164016144521001),
 (9190, 0.01163905267528243),
 (7784, 0.011615936800655327),
 (6731, 0.011615704762363135),
 (5405, 0.01155098727669651),
 (757, 0.011522978718635375),
 (5170, 0.011511643316976553),
 (5907, 0.011453287353439196),
 (4313, 0.011433667585398889),
 (9197, 0.011374536397827255),
 (5774, 0.01130775075185863),
 (1481, 0.011300199645701246),
 (3794, 0.011281248574402266),
 (4755, 0.011276114565850096),
 (8028, 0.011196043764090946),
 (7819, 0.01119585483682604),
 (3037, 0.011193386684488093),
 (9470, 0.011132046032067033),
 (9003, 0.011088438009196433),
 (5531, 0.011074578311398804),
 (2961, 0.011074148899369515),
 (7734, 0.011053359362480714),
 (2896, 0.011028820062927887),
 (6987, 0.011013282076765281),
 (259, 0.010991261136392663),
 (5185, 0.01097694207512944),
 (1461, 0.01097140642007784),
 (9531, 0.010953442523822078),
 (464, 0.010938965278038882),
 (1847, 0.010922152214850298),
 (4849, 0.010886430396251296),
 (5988, 0.010874534924689093),
 (7534, 0.010871640219374633),
 (8186, 0.01086150508294264),
 (4676, 0.010851979344485499),
 (3556, 0.010851926907921246),
 (902, 0.01079188316116076),
 (1187, 0.010779062300785609),
 (1703, 0.010774466000728025),
 (2565, 0.010773964435642058),
 (1558, 0.01072939043541113),
 (8064, 0.010668223111392958),
 (3929, 0.010661422609114124),
 (5452, 0.01062492208510771),
 (8478, 0.010602097718853716),
 (2873, 0.010596943485717353),
 (1453, 0.010578144524816077),
 (2848, 0.010552193406275563),
 (3933, 0.010538569794802577),
 (5168, 0.010533460608259278),
 (7143, 0.010522119396183706),
 (13, 0.010515673018000726),
 (4942, 0.010506177360526985),
 (3576, 0.010506072073934431),
 (6513, 0.010499598278130021),
 (4806, 0.01048282632597951),
 (6825, 0.010471199878844373),
 (2218, 0.010466091884815459),
 (311, 0.010462274225291748),
 (2874, 0.01045758569586653),
 (7223, 0.010457439933559055),
 (1877, 0.01044259896299901),
 (2980, 0.010429177457697515),
 (4127, 0.010420331874176788),
 (49, 0.010405964455322714),
 (1184, 0.010404845782537376),
 (6589, 0.010395303655312237),
 (3665, 0.010394947995516157),
 (1738, 0.01037435201526856),
 (8426, 0.01037267598117881),
 (9224, 0.010363661826842212),
 (9586, 0.010355750688836067),
 (5899, 0.0103267495214748),
 (662, 0.010317805566520689),
 (7248, 0.010278789164579642),
 (4515, 0.010278276897764513),
 (6683, 0.010266019563903628),
 (3585, 0.010234615420668459),
 (2478, 0.010232971934536247),
 (6242, 0.010231237785941538),
 (2638, 0.010209063306992007),
 (888, 0.01016853342731057),
 (481, 0.010162086262580958),
 (527, 0.010155377434056603),
 (1498, 0.010151717086682051),
 (666, 0.010150043435728315),
 (1151, 0.010148917984234049),
 (6064, 0.010147851460750095),
 (2136, 0.01014414050312246),
 (3591, 0.010137683611441907),
 (1770, 0.010125292149994528),
 (6049, 0.010102664931716805),
 (7732, 0.010069445438890691),
 (9860, 0.01006632670111883),
 (2623, 0.01005550345409843),
 (446, 0.010043502014126944),
 (9430, 0.01001626738478309),
 (3033, 0.009998637229972525),
 (3199, 0.00999381322452844),
 (8917, 0.00998505909243949),
 (8526, 0.00998165271213012),
 (9816, 0.009975469445063941),
 (9941, 0.009966986956311678),
 (5054, 0.009961365476986093),
 (1752, 0.009937467202863294),
 (6617, 0.009930132784059784),
 (4544, 0.009921005169444696),
 (8004, 0.009899457798533701),
 (6715, 0.009896956567385134),
 (8986, 0.009894536580503306),
 (3279, 0.00987726048845064),
 (9829, 0.00987558117621221),
 (7882, 0.009869081181654839),
 (607, 0.009857109551977942),
 (9127, 0.009852262379621356),
 (4214, 0.009838187567072552),
 (3509, 0.009823601320521477),
 (8473, 0.009819037271725397),
 (5963, 0.009797540786564314),
 (5740, 0.009774477191071282),
 (83, 0.009755573022765949),
 (438, 0.009747716434810656),
 (6256, 0.009689159827801275),
 (8983, 0.00967984900851279),
 (4934, 0.00967428145804761),
 (5267, 0.009647172593537392),
 (264, 0.009641475807267865),
 (626, 0.009617686195274151),
 (6398, 0.009614554811973229),
 (8956, 0.009613279924109357),
 (830, 0.009605811998538997),
 (2381, 0.009605723139287332),
 (4477, 0.009595478807017898),
 (2135, 0.009592321736739198),
 (4793, 0.009584051233797426),
 (7536, 0.009572022828061405),
 (3264, 0.009561371907857732),
 (7519, 0.009538305000475738),
 (2869, 0.009530720429117042),
 (3831, 0.009504911475997881),
 (7162, 0.009503976098287204),
 (6086, 0.009502542880868572),
 (6814, 0.00950253983805376),
 (1115, 0.00949611407185403),
 (6819, 0.009493708962070612),
 (8816, 0.009488128045239425),
 (2806, 0.00948801960091414),
 (5454, 0.009478913829642041),
 (8924, 0.009455581168982912),
 (87, 0.00944658738851179),
 (693, 0.00943432668233281),
 (6974, 0.009427996087378052),
 (3138, 0.009418908794433401),
 (3769, 0.00940826002721245),
 (1728, 0.00938318128790628),
 (6413, 0.009367689027263964),
 (4715, 0.009366487431605484),
 (6484, 0.009348002313384403),
 (9363, 0.009342513478539885),
 (8073, 0.009341747463429632),
 (5165, 0.009335225358234386),
 (6787, 0.009289987800507148),
 (9256, 0.009288330761328055),
 (1473, 0.0092692811076043),
 (1448, 0.009265353926573655),
 (2146, 0.009260611735850702),
 (8177, 0.00925689689305837),
 (4320, 0.009251063437889335),
 (6035, 0.009249972555171307),
 (370, 0.009246547650690402),
 (2323, 0.009244308199378921),
 (8104, 0.009242604171524548),
 (7792, 0.00922589067470297),
 (1819, 0.00920597432275133),
 (8119, 0.009177499632961108),
 (3496, 0.009164115545768665),
 (8970, 0.009163007805973398),
 (3634, 0.009145252355435857),
 (1023, 0.009144356751365544),
 (4751, 0.009142596804846448),
 (8859, 0.009120700367735206),
 (3568, 0.009119986440982239),
 (9617, 0.009063167438913144),
 (3978, 0.009048917742295718),
 (5138, 0.009045612333313831),
 (9065, 0.009026457933394341),
 (1547, 0.009021814146306678),
 (4133, 0.009017988106447706),
 (3012, 0.009015040247173605),
 (5856, 0.009007314909673242),
 (3598, 0.008967615765482322),
 (1123, 0.008957315172649152),
 (8143, 0.008953093765786048),
 (86, 0.008940605814013073),
 (6651, 0.008936179914210883),
 (7709, 0.008905166256462912),
 (1279, 0.008890523519272392),
 (6732, 0.008888021738237738),
 (3187, 0.008879604127216811),
 (9599, 0.008871880524407865),
 (1671, 0.008857301273682337),
 (7651, 0.008853945653278024),
 (7618, 0.00883808516305544),
 (332, 0.008837045813704938),
 (2960, 0.008834527325352219),
 (8959, 0.008834527325352219),
 (1075, 0.008819553552681866),
 (5660, 0.00881541449969497),
 (277, 0.008801268688454223),
 (7488, 0.008784102986633673),
 (7013, 0.008780209174584094),
 (958, 0.00877961233419983),
 (576, 0.00876191060092335),
 (3412, 0.008758469838330589),
 (5417, 0.008751114617587666),
 (8818, 0.008746264734612076),
 (8799, 0.008741028450135763),
 (4871, 0.00873369625755588),
 (2109, 0.00872499638397094),
 (6992, 0.008723337738497263),
 (9341, 0.008704049303672488),
 (7434, 0.008689921591386358),
 (9282, 0.008688969218854842),
 (579, 0.008663727434147051),
 (5412, 0.00865577442991108),
 (294, 0.008635155485916167),
 (5930, 0.00862855589484713),
 (7790, 0.008613637707478238),
 (3776, 0.008613088349281765),
 (857, 0.008609523000664237),
 (7699, 0.008601706631516607),
 (8872, 0.008593881618026185),
 (2517, 0.008585536797702919),
 (9926, 0.008570275628737325),
 (1181, 0.008563677209685755),
 (7303, 0.008563619581618682),
 (9276, 0.008561836686580986),
 (1706, 0.008556951209929673),
 (6602, 0.008552125713592774),
 (7525, 0.008536762420172095),
 (186, 0.008531439750878266),
 (9859, 0.008518181018245464),
 (3607, 0.008512407589669911),
 (3405, 0.008502533660707846),
 (2349, 0.008502098235217734),
 (6706, 0.008481866941206971),
 (9169, 0.00843775976948741),
 (7116, 0.008419491304343728),
 (6080, 0.008410368593430285),
 (6955, 0.008408172782622519),
 (3688, 0.008399626502712934),
 (6160, 0.008392289800919304),
 (4541, 0.008385412467132997),
 (7780, 0.008385327505137215),
 (6356, 0.008382474784775768),
 (8801, 0.008379640526741026),
 (6464, 0.008374295677703775),
 (6907, 0.008371159168139514),
 (7495, 0.008368519122118835),
 (7832, 0.008361377472128662),
 (5397, 0.008343381742252057),
 (3473, 0.008335907045302618),
 (2122, 0.00833108589824042),
 (2159, 0.008315618504478007),
 (5043, 0.00830822755242164),
 (274, 0.008301733145345689),
 (4342, 0.008298869220205894),
 (6377, 0.00827669309749404),
 (6127, 0.008269032715841963),
 (803, 0.00826695962064921),
 (6737, 0.008249205377340602),
 (5236, 0.008248439563231862),
 (6154, 0.008244392866588854),
 (1937, 0.008242913586189095),
 (573, 0.008233200395418418),
 (9579, 0.008232280261008203),
 (2171, 0.00822963990091112),
 (4098, 0.008226015348730343),
 (4165, 0.008209982963848275),
 (582, 0.00819795996497039),
 (1582, 0.008187869955007681),
 (2842, 0.008183470904902741),
 (8902, 0.008171592326934655),
 (358, 0.008163225208742833),
 (9275, 0.008160948134298492),
 (5525, 0.008158330790601399),
 (8504, 0.008143864884920715),
 (7839, 0.008138304420296892),
 (551, 0.008130775359527474),
 (1080, 0.00812961578963624),
 (559, 0.008118138397747984),
 (7970, 0.008109659556695029),
 (9573, 0.008097643901643808),
 (4206, 0.00809437580483291),
 (7934, 0.008092259231886726),
 (2110, 0.008088617455524468),
 (3771, 0.008081577759876037),
 (2983, 0.008054961766695817),
 (9625, 0.008040890470210614),
 (2203, 0.008036804866452267),
 (2394, 0.00802683008121725),
 (8428, 0.008025027882936601),
 (4337, 0.008023772889143056),
 (7393, 0.008023501856262662),
 (779, 0.008015459717862604),
 (8655, 0.008014475971754274),
 (9383, 0.008010030444050732),
 (7782, 0.008001373449275272),
 (92, 0.008000384781405532),
 (1953, 0.007997837236401581),
 (849, 0.007991829205657029),
 (6443, 0.007990498933326722),
 (6749, 0.007985011475068375),
 (7742, 0.00798485721722575),
 (7486, 0.007983982069973665),
 (8736, 0.007982893982891755),
 (5698, 0.007980330236232834),
 (2815, 0.007977569351950306),
 (3523, 0.0079765356386164),
 (9857, 0.007975840081219852),
 (5174, 0.007974972879244533),
 (9181, 0.007974454085597),
 (8405, 0.007971222871203394),
 (7138, 0.007970934718159623),
 (5771, 0.007964539397276628),
 (8942, 0.007960653592409727),
 (507, 0.007955044861579129),
 (480, 0.007949605993913453),
 (7373, 0.00794604244621029),
 (9422, 0.00793869550185352),
 (2680, 0.007934812446786163),
 (4504, 0.007913764839353042),
 (1470, 0.007890479284211323),
 (735, 0.007876254321760904),
 (9451, 0.007875243941271452),
 (9230, 0.007874840357584833),
 (5394, 0.007866491759861533),
 (1299, 0.007865081333386448),
 (8712, 0.007863798253033962),
 (3272, 0.007859271864490916),
 (7450, 0.007858745123615406),
 (6235, 0.00784408006446299),
 (8779, 0.007823289724900243),
 (8149, 0.007818716616506446),
 (729, 0.00781635329003633),
 (9413, 0.007799728150521976),
 (6646, 0.007786827057879068),
 (9925, 0.007786308116987938),
 (5254, 0.007781415403898654),
 (4232, 0.007781252711445905),
 (1259, 0.007780209746100351),
 (4291, 0.007773947969357115),
 (5059, 0.007764818949197139),
 (6829, 0.007763661600927352),
 (4722, 0.007760839148186881),
 (7635, 0.007747559247819959),
 (170, 0.007747159710098271),
 (6251, 0.0077415242118128455),
 (8200, 0.007737085824881435),
 (316, 0.007731821618030486),
 (6989, 0.007725419202538159),
 (500, 0.007721946347537464),
 (6431, 0.007721370696861931),
 (1345, 0.007717061029462761),
 (7206, 0.007716016475657254),
 (1287, 0.007703565899194883),
 (3572, 0.007697217045637712),
 (6200, 0.007689785297971411),
 (3724, 0.007678735670205502),
 (2485, 0.007662617037785117),
 (6134, 0.007661457759369572),
 (7453, 0.007654791613056919),
 (8863, 0.0076541394201467255),
 (8640, 0.007653574139118654),
 (2167, 0.007649447332979667),
 (5440, 0.0076458937014199065),
 (5354, 0.007645227162605398),
 (5446, 0.007638499099755191),
 (2400, 0.007619653438242904),
 (7646, 0.007613293661472798),
 (4550, 0.007610279167179676),
 (4832, 0.007606859730926477),
 (5521, 0.007587618991149167),
 (8291, 0.007579763991809714),
 (3048, 0.007559878968757596),
 (1144, 0.007558198990539071),
 (3370, 0.007556446344275913),
 (3040, 0.007554181474144116),
 (6264, 0.007551857103893679),
 (9283, 0.007547263975955031),
 (9071, 0.007546584497572051),
 (3583, 0.0075371805441077355),
 (7867, 0.007536991773749886),
 (585, 0.007533821153826826),
 (9095, 0.007529396232041503),
 (9195, 0.007527864487580764),
 (9516, 0.007516783748188002),
 (7704, 0.007503441454173343),
 (7754, 0.007496322431379309),
 (9072, 0.007488025909359494),
 (8738, 0.00747864191202181),
 (9574, 0.00747447739924576),
 (5455, 0.007473374321817706),
 (5415, 0.007468749026953755),
 (2504, 0.007448086011719068),
 (4112, 0.007440828870695423),
 (3555, 0.0074391984688055),
 (387, 0.00743342582055582),
 (1225, 0.007432114905556231),
 (5833, 0.007429161269216652),
 (1796, 0.007420029597598694),
 (1652, 0.007404646399692669),
 (9657, 0.007404637203077696),
 (8108, 0.007401925865011514),
 (2247, 0.007395100511472689),
 (9144, 0.007368998081855337),
 (4352, 0.007366821746339401),
 (5904, 0.007366396811794854),
 (1435, 0.007364533463065701),
 (5448, 0.007363841811727016),
 (7008, 0.007357777793085498),
 (920, 0.007348004432046656),
 (9412, 0.007343797023227981),
 (6610, 0.00734238724472774),
 (6839, 0.007334414543892091),
 (1826, 0.007330223709284789),
 (2, 0.00732992608933115),
 (7317, 0.0073286551265092014),
 (9777, 0.00732864113995884),
 (6079, 0.007327912249595816),
 (1935, 0.007320910581554831),
 (4186, 0.007318743322977748),
 (4305, 0.007316521727870854),
 (5792, 0.007302341584381152),
 (3397, 0.007297231232830641),
 (5578, 0.007292430265303701),
 (6522, 0.007289014185599574),
 (3772, 0.007285522986690027),
 (4338, 0.007285278873381503),
 (2947, 0.007283594052580927),
 (3232, 0.007281740725839259),
 (5900, 0.007277621975334907),
 (5105, 0.007265985181143686),
 (8979, 0.0072559219657505085),
 (1890, 0.007254197147867039),
 (27, 0.0072527578180679435),
 (7069, 0.007251893726678596),
 (5809, 0.007243531670008622),
 (3170, 0.00723553857428094),
 (5342, 0.007233855395350726),
 (7828, 0.007226627597115412),
 (8253, 0.007225578210524635),
 (5443, 0.007219311083352498),
 (6752, 0.007209681522291148),
 (578, 0.00719129177262871),
 (491, 0.007186955189346642),
 (1478, 0.0071821193009073536),
 (3294, 0.007176835475830928),
 (2572, 0.007176654703080849),
 (1722, 0.007158870020354714),
 (1535, 0.007157740685233891),
 (6149, 0.007156860128523438),
 (8107, 0.0071542823697192445),
 (4717, 0.007139635507024171),
 (1428, 0.007136527943226738),
 (8791, 0.007135692894293135),
 (9483, 0.007133433517031367),
 (921, 0.007120793857569495),
 (253, 0.007116254015238494),
 (1867, 0.007109096887357341),
 (5882, 0.007108854330164378),
 (2769, 0.007100559528657267),
 (4841, 0.007091897047273526),
 (8620, 0.007088747634177499),
 (9317, 0.007079980573116823),
 (5127, 0.007076150616000086),
 (6713, 0.007075982225090738),
 (1965, 0.0070504131797654804),
 (4175, 0.007036907821458145),
 (6186, 0.007034041890428102),
 (1689, 0.007027578390203667),
 (664, 0.007016206530757221),
 (3377, 0.007011306867986549),
 (7890, 0.007010503572037384),
 (9186, 0.007010022631210516),

In [29]:
sim_scores = sim_scores[1:31]

In [30]:
sim_scores

[(1178, 0.14992200033931688),
 (4324, 0.04021684976693453),
 (5433, 0.039311985383549956),
 (29, 0.039263281451062115),
 (6977, 0.03890199598661835),
 (8364, 0.035184062488509214),
 (2891, 0.0338554146883491),
 (6711, 0.031712633383547024),
 (1914, 0.030150463453486608),
 (5476, 0.029117000357142646),
 (5689, 0.027081639574887587),
 (2624, 0.026825525125295048),
 (724, 0.02674887043631316),
 (4473, 0.025911994676770758),
 (9216, 0.025601002253174937),
 (3998, 0.025554387762630137),
 (2587, 0.025546375052027726),
 (4618, 0.02537172801173615),
 (7765, 0.024745228517596127),
 (4464, 0.024057529584514546),
 (4396, 0.023997651259148142),
 (8653, 0.02341847975634212),
 (8191, 0.023222283257004456),
 (7515, 0.02287073390869033),
 (5330, 0.021847090088984458),
 (251, 0.021793539674849698),
 (6822, 0.021495331464793044),
 (1874, 0.021411146240112207),
 (7731, 0.020920943247186612),
 (3291, 0.020754939932866246)]

In [31]:
movie_indices = [i[0] for i in sim_scores]

In [32]:
movie_indices

[1178,
 4324,
 5433,
 29,
 6977,
 8364,
 2891,
 6711,
 1914,
 5476,
 5689,
 2624,
 724,
 4473,
 9216,
 3998,
 2587,
 4618,
 7765,
 4464,
 4396,
 8653,
 8191,
 7515,
 5330,
 251,
 6822,
 1874,
 7731,
 3291]

In [34]:
titles.iloc[movie_indices]

1178     The Godfather: Part II
4324                       Made
5433         Johnny Dangerously
29               Shanghai Triad
6977            Queen of Hearts
8364                       Fury
2891             American Movie
6711                   Mobsters
1914    The Godfather: Part III
5476                    8 Women
5689        The Young Americans
2624           The Color Purple
724                     Thinner
4473              Harlem Nights
9216        Running Out of Time
3998          Jaws: The Revenge
2587              Summer of Sam
4618                   3 Ninjas
7765            The Kid Brother
4464            Family Business
4396          Moon Over Parador
8653               Violent City
8191                     Eulogy
7515         The Valachi Papers
5330          Road to Perdition
251              The Jerky Boys
6822               The Freshman
1874               Halloween II
7731              Bright Future
3291                 Soft Fruit
Name: title, dtype: object